// <auto-generated />
using System;
using Avaliacao.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Avaliacao.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Avaliacao.Model.RickMory", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dimensao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImagemMorty")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ImagemRick")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MortyNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RickNome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("RickMory");
                });
#pragma warning restore 612, 618
        }
    }
}
